# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: "Hailton &bull; UI and UX Designer"
description: "UI and UX Designer"
url: "http://hailtonsilva.github.io/"
#markdown: redcarpet #rdiscount alternative
paginate: 10 # pagination basted on number of posts
permalink: pretty
pygments: true
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss'] # files to exclude


